apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pyserver-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: pyserver-nodeport
          servicePort: 8080

    